#!/bin/bash

echo "=========================================="
echo "📊 Featured Movies Upload Verification"
echo "=========================================="
echo ""

echo "📋 Movies to be uploaded as FEATURED:"
echo "------------------------------------------"
echo ""
echo "🎬 Movie 1: 1917"
echo "   • Dubbed by: Gaheza Simba"
echo "   • Rating: Gaheza Simba"
echo "   • Download: https://www.mediafire.com/file/fsp205e7qa7omks/1917.mp4/file"
echo "   • Embed: <iframe src=\"https://rwaflix.embedseek.com/#cgj1v\" width=\"100%\" height=\"100%\" frameborder=\"0\" allowfullscreen></iframe>"
echo ""
echo "🎬 Movie 2: Rosario"
echo "   • Dubbed by: Sankara"
echo "   • Rating: Sankara"
echo "   • Download: https://www.mediafire.com/file/qdl63hzvt6rpvwy/Rosario.mp4/file"
echo "   • Embed: <iframe src=\"https://rwaflix.embedseek.com/#vl8cw\" width=\"100%\" height=\"100%\" frameborder=\"0\" allowfullscreen></iframe>"
echo ""

echo "=========================================="
echo "📂 Files Created:"
echo "------------------------------------------"
ls -lh upload_movies*.py upload_featured_movies.* FEATURED_MOVIES_SETUP.md 2>/dev/null | awk '{print "   " $9 " (" $5 ")"}'
echo ""

echo "=========================================="
echo "⚙️  SQL Commands Summary:"
echo "------------------------------------------"
echo "1. UPDATE movies SET featured = false;"
echo "2. INSERT 1917 with Gaheza Simba rating"
echo "3. INSERT Rosario with Sankara rating"
echo ""

echo "=========================================="
echo "✅ NEXT STEPS:"
echo "------------------------------------------"
echo "1. Set SUPABASE_ANON_KEY environment variable"
echo "2. Run: python3 upload_movies_fixed.py"
echo "   OR"
echo "   Execute SQL commands in your database"
echo "3. Verify at: www.rwaflix.store/admin"
echo "   Credentials: admin@admin.com / henryhappy"
echo ""

echo "=========================================="
